### ISSUE TITLE
0.0.14 crashes react native

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#18]
looks like some dependency is still relying on a core node module (`url`) 

![glass](https://cloud.githubusercontent.com/assets/54157/20485344/19cb1126-afc9-11e6-9604-0f9b283f8c95.png)

**Comment by joeferraro** [comment]
probably best to set up a lightweight RN project for you to test with before pushing patches

**Comment by kidtsunami** [comment]
Ok spinning up a new react-native project
