### ISSUE TITLE
support non-communities chatter requests

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#19]
non-communities: https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickstart_connecting.htm

communities: https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickstart_communities.htm

**Comment by kidtsunami** [comment]
Handled in v0.1.3

It's merely a URL change.
