### ISSUE TITLE
Missing catch block in fetchJSON promise chain

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#22]
We need to add a `catch` block to the `fetchJSON` promise chain here: https://github.com/kidtsunami/fetch-salesforce/blob/master/src/lib/fetcher.ts#L118

**Comment by joeferraro** [comment]
```js
.catch(err => reject(err));
```

should suffice

**Comment by kidtsunami** [comment]
Resolved in 35077e7
