### ISSUE TITLE
Support X-Connect-Bearer-Urls header for chatter retrieve

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#23]
We need the ability to set the [`X-Connect-Bearer-Urls`](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_requesting_bearer_token_url.htm#kanchor36) header in order to get public-facing URLs for static resources. For now, I have a hack in place but it'd be great to support this officially. 

hack (line 25 of fetchChatter.js):
```js
headers: {
  'X-Connect-Bearer-Urls': true
}
```

**Comment by kidtsunami** [comment]
fetchChatter.retrieve now takes an optional boolean parameter of connectBearerUrls.

If connectBearerUrls is truthy, we add the header key value pair 'X-Connect-Bearer-Urls': true

Here is some test code calling it with connectBearerUrls = true:
```javascript
let expectedURL = 'https://instanceURL/test/services/data/v37.0/connect/communities/avalidcommunityid/chatter/feeds/news/me/feed-elements';
let expectedOptions = {
    headers: { 'X-Connect-Bearer-Urls': 'true' },
    method: 'GET',
    cache: 'no-cache'
};
let connectBearerUrls = true;

return fetchChatter.retrieve('feeds/news/me/feed-elements', connectBearerUrls)
    .then((result) => {
        expect(result).toBe('success');

        expect(fetchJSONStub.calledOnce).toBeTruthy();
        expect(fetchJSONStub.getCall(0).args[0]).toEqual(expectedURL);
        expect(fetchJSONStub.getCall(0).args[1]).toEqual(expectedOptions);
    });
```
