### ISSUE TITLE
Promise rejection control flow seems broken

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#24]
Getting the following warning when refreshing access token, can you please investigate @kidtsunami?

![glass](https://cloud.githubusercontent.com/assets/54157/22483502/96f27fe2-e7cb-11e6-8768-68266ef3135f.jpg)

**Comment by joeferraro** [comment]
Bluebird documentation on the warning: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

**Comment by kidtsunami** [comment]
give v0.1.1 a try, I think I tracked down the errant Promise in 2dd619bba55cc799b799205eb067c44c9778e3a6

**Comment by kidtsunami** [comment]
@joeferraro did this help?

**Comment by joeferraro** [comment]
@kidtsunami still getting this on an expired access token

**Comment by kidtsunami** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212034-220717640_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by kidtsunami** [comment]
@joeferraro I'm unable to reproduce, I revoke the access token and refresh just fine (though I found a separate bug around doing multiple refreshes, look for a new release soon).

**Comment by joeferraro** [comment]
I'm pretty sure it has to do with there being outstanding requests + an expired token (the buffer and retry flow).

**Comment by kidtsunami** [comment]
Easiest way for me to reliably get some outstanding requests going?

**Comment by kidtsunami** [comment]
flails and publishes fetch-salesforce@0.1.4

**Comment by joeferraro** [comment]
So, 0.1.5 does not seem to fix this issue. I think we need to do a review of the promise/request and resolve/reject/exception handling control flow, as it's difficult for me to follow how/whether we resolve/reject the original promises returned when a client makes a basic request. As an example, when the app has a bad refresh token, an exception is thrown and I get a number of warnings telling me `a promise was rejected with a non-error` in the `refreshAccessToken` flow.

![glass_and_iphone_7_ _ios_10_2__14c89_](https://cloud.githubusercontent.com/assets/54157/22570966/a86d2ae6-e96b-11e6-951f-91b7832f8f78.jpg)

![glass_and_iphone_7_ _ios_10_2__14c89_](https://cloud.githubusercontent.com/assets/54157/22570982/ba2c7c64-e96b-11e6-9893-ce925e9b293e.jpg)
