### ISSUE TITLE
Enhancement: add support for optional OAuth params like login_hint

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#26]
see https://developer.salesforce.com/page/Digging_Deeper_into_OAuth_2.0_on_Force.com#Obtaining_an_Access_Token_in_a_Browser_or_Native_Application_.28User-Agent_Flow.29

**Comment by kidtsunami** [comment]
Resolved by c91f3f13d8be7e9015e0bafa6e2433cb81e1ecc4

**Comment by kidtsunami** [comment]
yarn upgrade fetch-salesforce@0.1.2
