### ISSUE TITLE
token refresh callback

### ISSUE THREAD

**Issue by joeferraro** [kidtsunami/fetch-salesforce#5]
client should be able to assign a callback to token refresh

**Comment by kidtsunami** [comment]
Is a callback necessary as it is a Promise?

**Comment by joeferraro** [comment]
ideally, the client isn't refreshing the token explicitly. a 401 should prompt this library to refresh the token

**Comment by kidtsunami** [comment]
➤ David Helmer commented:
Going to use Events Emitter https://rymc.io/2011/04/16/emitting-custom-events-in-node-js/
